clear;
clc;

%% Analysis settings
Site = #; %(Selected site number)
nBoot = 500;

aep = [0.5 0.2 0.1 0.02 0.01];

gridResolution = 100;

xLim = [0 20];
yLim = [0 300];

%% Load bootstrap results
inputFile = sprintf( ...
    'Results_site%d_bootstrap_sensitivity.mat', Site);

load(inputFile);

%% Determine output dimensions
nAEP = numel(aep);

% Run the first bootstrap to determine the ensemble output size
sampleOut = relative_contribution_single_bootstrap( ...
    'Grid', Grid, ...
    'AEP_P1', AEP_P1(:,:,1), ...
    'AEP_P2', AEP_P2(:,:,1), ...
    'Ensemble', Ensemble(:,:,:,1), ...
    'thres_AR_Hmo', thres_AR_Hmo(1,1), ...
    'thres_non_AR_Hmo', thres_non_AR_Hmo(1,1), ...
    'thres_AR_RF', thres_AR_RF(1,1), ...
    'thres_non_AR_RF', thres_non_AR_RF(1,1), ...
    'aep', aep, ...
    'Resolution', gridResolution, ...
    'x_L_lim', xLim(1), ...
    'x_U_lim', xLim(2), ...
    'y_L_lim', yLim(1), ...
    'y_U_lim', yLim(2), ...
    'Plot', false, ...
    'PlotField', 'Z_AR_1');

nEnsemble = size(sampleOut.RC_Ensemble, 1);

%% Preallocate results
RC_Ensemble = NaN(nEnsemble, nAEP, nBoot);
RC_RF_marginal = NaN(nBoot, nAEP);
RC_Hmo_marginal = NaN(nBoot, nAEP);

% Store the first bootstrap result
RC_Ensemble(:,:,1) = sampleOut.RC_Ensemble;
RC_RF_marginal(1,:) = sampleOut.RC_RF_marginal;
RC_Hmo_marginal(1,:) = sampleOut.RC_Hmo_marginal;

%% Parallel bootstrap analysis
pool = gcp('nocreate');

if isempty(pool)
    nWorkers = max(1, feature('numcores') - 1);
    parpool(nWorkers);
end

parfor b = 2:nBoot

    out = relative_contribution_single_bootstrap( ...
        'Grid', Grid, ...
        'AEP_P1', AEP_P1(:,:,b), ...
        'AEP_P2', AEP_P2(:,:,b), ...
        'Ensemble', Ensemble(:,:,:,b), ...
        'thres_AR_Hmo', thres_AR_Hmo(b,1), ...
        'thres_non_AR_Hmo', thres_non_AR_Hmo(b,1), ...
        'thres_AR_RF', thres_AR_RF(b,1), ...
        'thres_non_AR_RF', thres_non_AR_RF(b,1), ...
        'aep', aep, ...
        'Resolution', gridResolution, ...
        'x_L_lim', xLim(1), ...
        'x_U_lim', xLim(2), ...
        'y_L_lim', yLim(1), ...
        'y_U_lim', yLim(2), ...
        'Plot', false, ...
        'PlotField', 'Z_AR_1');

    RC_Ensemble(:,:,b) = out.RC_Ensemble;
    RC_RF_marginal(b,:) = out.RC_RF_marginal;
    RC_Hmo_marginal(b,:) = out.RC_Hmo_marginal;

end

%% Median AR contribution for each bootstrap
% Median across ensemble points for each AEP and bootstrap realization
Median_RC_Ensemble = squeeze( ...
    median(RC_Ensemble, 1, 'omitnan'))';

%% Plot bootstrap distributions
selectedAEP = [0.5 0.01];   % 2-year and 100-year events

outDir = 'Bootstrap_RC_Distributions';

if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% Common histogram bins
edges = 0:2:100;

for j = 1:numel(selectedAEP)

    [~, idxAEP] = min(abs(aep - selectedAEP(j)));

    currentAEP = aep(idxAEP);
    returnPeriod = 1 / currentAEP;

    % Bootstrap distributions
    ensembleData = Median_RC_Ensemble(:,idxAEP);
    rfData = RC_RF_marginal(:,idxAEP);
    hmoData = RC_Hmo_marginal(:,idxAEP);

    ensembleData = ensembleData(isfinite(ensembleData));
    rfData = rfData(isfinite(rfData));
    hmoData = hmoData(isfinite(hmoData));

    datasets = {
        ensembleData, ...
        rfData, ...
        hmoData};

    labels = {
        'Median Ensemble RC', ...
        'RF Marginal RC', ...
        'nTWL Marginal RC'};

    %% Common y-axis limit
    maxProb = 0;

    for m = 1:numel(datasets)

        counts = histcounts( ...
            datasets{m}, ...
            edges, ...
            'Normalization', 'probability');

        maxProb = max(maxProb, max(counts));

    end

    yLimCommon = [0 maxProb * 1.15];

    %% Comparison figure
    fig = figure( ...
        'Color', 'w', ...
        'Position', [100 100 1400 420]);

    tiledlayout( ...
        1, 3, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    for m = 1:numel(datasets)

        nexttile;

        plotHistWithCI( ...
            datasets{m}, ...
            edges, ...
            yLimCommon, ...
            labels{m});

    end

    sgtitle( ...
        sprintf( ...
            'Relative Contribution Distributions: %g-year Event', ...
            returnPeriod), ...
        'FontName', 'Calibri', ...
        'FontSize', 16, ...
        'FontWeight', 'bold');

    %% Save figure
    baseName = sprintf( ...
        'Site_%d_RC_Comparison_RP_%gyr', ...
        Site, ...
        returnPeriod);

    savefig( ...
        fig, ...
        fullfile(outDir, [baseName '.fig']));

    exportgraphics( ...
        fig, ...
        fullfile(outDir, [baseName '.png']), ...
        'Resolution', 300);

end

disp('Bootstrap relative-contribution analysis complete.');


%% Local function
function plotHistWithCI(data, edges, yLimCommon, labelStr)

histogram( ...
    data, ...
    edges, ...
    'Normalization', 'probability', ...
    'FaceColor', [0.2 0.4 0.8], ...
    'FaceAlpha', 0.7, ...
    'EdgeColor', 'w');

hold on;

% Median and 95% bootstrap interval
medianValue = median(data, 'omitnan');
ci = prctile(data, [2.5 97.5]);

% Shade bootstrap interval
patch( ...
    [ci(1) ci(2) ci(2) ci(1)], ...
    [yLimCommon(1) yLimCommon(1) yLimCommon(2) yLimCommon(2)], ...
    [0.9 0.6 0.2], ...
    'FaceAlpha', 0.15, ...
    'EdgeColor', 'none');

% Interval bounds
xline( ...
    ci(1), ...
    '--', ...
    'Color', [0.6 0.3 0], ...
    'LineWidth', 1.5);

xline( ...
    ci(2), ...
    '--', ...
    'Color', [0.6 0.3 0], ...
    'LineWidth', 1.5);

% Median
xline( ...
    medianValue, ...
    '-', ...
    sprintf('Median = %.1f%%', medianValue), ...
    'Color', 'k', ...
    'LineWidth', 2, ...
    'LabelVerticalAlignment', 'top', ...
    'FontSize', 10);

xlabel( ...
    'AR Relative Contribution (%)', ...
    'FontName', 'Calibri', ...
    'FontSize', 13);

ylabel( ...
    'Probability', ...
    'FontName', 'Calibri', ...
    'FontSize', 13);

title( ...
    labelStr, ...
    'FontName', 'Calibri', ...
    'FontSize', 14);

xlim([0 100]);
ylim(yLimCommon);

grid on;
box on;

set(gca, ...
    'FontName', 'Calibri', ...
    'FontSize', 12);

hold off;

end